mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from todos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('todos/', include('todos.urls')),
    path('accounts/signup/', views.signup, name = 'signup'),
]

todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('new/', views.new, name = 'new'),
]

todos/models.py
from django.db import models
from django.contrib.auth.models import User


    
class Todo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default = -1)
    todo_text = models.CharField(max_length = 2000)
    pub_date = models.DateTimeField('creation time')
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text

todos/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

from .models import Todo

@login_required
def index(request):
    if request.method == 'GET':
        todos_list = Todo.objects.filter(author=request.user).order_by('-pub_date')
        context = {'todos_list': todos_list}
        return render(request, 'todos/index.html', context)
    else:
        t_id = request.POST['todo_id']
        t = Todo.objects.get(id=t_id)
        if "done" in request.POST:
            t.status = True
            t.save()
        if "delete" in request.POST:
            t.delete()
        return HttpResponseRedirect(reverse('todos:index'))
        

@login_required
def new(request):
    if request.method == 'POST':
        text = request.POST.get('todo_text', False)
        t = Todo(author = request.user, todo_text = text, pub_date = timezone.now())
        t.save()
        return HttpResponseRedirect(reverse('todos:index'))
    else:
        return render(request, 'todos/new.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('todos:index'))
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

todos/templates/todos/index.html
<nav>
	<a href="{% url 'todos:index' %}">TODOS</a>
	<a href="{% url 'logout' %}" style = "float:right"> Log Out</li>
</nav>
{% if todos_list %}
	<h4><a href= "{% url 'todos:new' %}"> New </a></h4>
    <ul style="list-style-type: none">
    {% for todo in todos_list %}
		<div>
			<li>
				<small>{{todo.pub_date}}</small><br>
				{{todo.todo_text}}
				<form method = "post">
				{% csrf_token %}
				<input type="hidden" name="todo_id" id="todo_id" value="{{todo.id}}">
				{% if todo.status is False %}
					<input type="submit" name="done" value="Mark as done!">
				{% else %}
					Completed!
				{% endif %}
				<input type="submit" name="delete" value="Delete!">
				</form>
			</li>
			<br><br>
		</div>
    {% endfor %}
    </ul>
{% else %}
	<h4><a href= "{% url 'todos:new' %}"> New </a></h4>
    <p>No todo created</p>
{% endif %}

todos/templates/todos/new.html
<form method="post" action={% url 'todos:new' %}>
	{% csrf_token %}
	Todo:
	</br>
	<input type="text" name="todo_text" required></br>
	<input type="submit" value="Submit">
</form>